
main_metric : 'T5_A'

eval:
  freq : 1
  data :
    name : 'MECCANO'
    split : 'test'

    feat_file : '/data1/qzhb/datasets/MECCANO/obj/Test'
    feature : 'FRCNN'
    feature_fps : 12
    feature_dim : 20

    forward_frame : 8
    past_frame : 40
    
    fps : 4
    batch_size : 128
    num_workers : 2
    cache : false


model:
  name : 'DCR'
  
  feat_dim: 20
  past_frame : 40
  anticipation_frame : 4
  action_frame : 4
  
  reasoner:
    name : 'transformer'
    d_model : 1024
    nhead : 16
    dff : 4096
    depth : 6
    dropout : 0.1
    pe_type : 'learnable'

  classifier:
    dropout: 0.4
    action: true
    verb: true
    noun : true

  loss:
    name : 'CE'
    verb : 0.5
    noun : 0.5
    feat_mse : 1.
    next_cls : 0.5
    smooth: 0.2